/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JavaMVCViews;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

import JavaMVCControllers.HelloWorldController;

/**
 *
 * @author AfzaalAhmad
 */
public class ErrorView extends JFrame implements HelloWorldViewInterface {

    // Create the class for the Controller
    private HelloWorldController controller = new HelloWorldController();
    private javax.swing.JScrollPane jScrollPane1;
    private JButton loadData;
    public JLabel myLabel;
    private JTextArea myMessage;
    private JButton writeData;

    /**
     * Creates new form HelloWorldView
     */
    public ErrorView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    public void initComponents() {

        myLabel = new JLabel();
        loadData = new JButton();
        jScrollPane1 = new JScrollPane();
        myMessage = new JTextArea();
        writeData = new JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("myFrame"); // NOI18N

        myLabel.setText("Ok, the text is currently not loaded...");

        loadData.setText("Load Data");
        loadData.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                loadDataMouseClicked(evt);
            }
        });

        myMessage.setColumns(20);
        myMessage.setRows(5);
        jScrollPane1.setViewportView(myMessage);

        writeData.setText("Write Data");
        writeData.addMouseListener(new MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                writeDataMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(myLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                                                        .addComponent(jScrollPane1))
                                                .addContainerGap())
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(loadData)
                                                .addGap(158, 158, 158))))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(154, 154, 154)
                                .addComponent(writeData)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(myLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(loadData)
                                .addGap(39, 39, 39)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(writeData)
                                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void loadDataMouseClicked(MouseEvent evt) {//GEN-FIRST:event_loadDataMouseClicked
        // TODO add your handling code here:
        try {
            String data = controller.getMessage();
            myLabel.setText(data);
            myLabel.setVisible(true);
        } catch (Exception er) {

        }
    }//GEN-LAST:event_loadDataMouseClicked

    public void writeDataMouseClicked(MouseEvent evt) {//GEN-FIRST:event_writeDataMouseClicked
        // TODO add your handling code here:
        String message = myMessage.getText();
        controller.writeMessage(message);
    }//GEN-LAST:event_writeDataMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new HelloWorldView().setVisible(true);
            }
        });
    }

    public void setVisible(boolean isVisible) {
        super.setVisible(isVisible);
    }

    @Override
    public void setMyLabel(String s) {
        myLabel.setText(s);
    }

}
